name: ajudante
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  device_apps: ^2.2.0
  flutter:
    sdk: flutter
  path: ^1.8.3
  provider: ^6.0.5
  sqflite: ^2.3.0
  url_launcher: ^6.2.2
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
